name: Validate
on: [workflow_call]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t tpubuilder --build-arg IMAGE=ubuntu:18.04 ./docker

    - name: Run Build in Custom Docker Container
      run: |
        docker run --rm -i \
          -v ${{ github.workspace }}:/workspace \
          tpubuilder /bin/bash -c "make libedgetpu"