name: Validate
on: [workflow_call]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t tpubuilder --build-arg IMAGE=ubuntu:18.04 ./docker

    - name: Run Build in Custom Docker Container
      run: |
        pwd && ls -la
        echo ${{ github.workspace }}
        docker run --rm -i \
          -v ${{ github.workspace }}/libedgetpu:/workspace \
          tpubuilder /bin/bash -c "ls -al /workspace && make -C /workspace libedgetpu"
    
    - name: Upload Build artifact
      uses: actions/upload-artifact@v3
      with:
        name: drivers
        path: libedgetpu/bazel-out
        retention-days: 1