name: Validate
on: [workflow_call]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Build in Custom Docker Container
      env:
        CPU: "k8"
        DOCKER_CPUS: "k8"
        DOCKER_IMAGE: "ubuntu:18.04"
        DOCKER_TARGETS: libedgetpu
      run: |
        make docker-build

    - name: Upload Build artifact
      uses: actions/upload-artifact@v3
      with:
        name: drivers
        path: out
        retention-days: 1